-- sim_wrapper_template.vhd
-- Generated by sim_bridge.py: the {toplevel} placeholder is replaced
-- with the user's entity name before this file is analysed.
--
-- Driving the clock from VHDL eliminates all per-half-period Python-to-
-- simulator GPI callbacks, cutting simulator step time ~10x.
--
-- clk_half_ns controls the virtual clock frequency at runtime.
-- sim_testbench.py writes dut.clk_half_ns.value whenever the panel's
-- [-]/[+] buttons are pressed; the VHDL process picks up the new value
-- on the next half-cycle, identical to the prior Python _dynamic_clock
-- behaviour.

library ieee;
use ieee.std_logic_1164.all;

entity sim_wrapper is
  generic (
    NUM_SWITCHES     : positive := 4;
    NUM_BUTTONS      : positive := 4;
    NUM_LEDS         : positive := 4;
    COUNTER_BITS     : positive := 24;
    CLK_HALF_NS_INIT : positive := 20
  );
  port (
    sw          : in  std_logic_vector(NUM_SWITCHES - 1 downto 0);
    btn         : in  std_logic_vector(NUM_BUTTONS  - 1 downto 0);
    led         : out std_logic_vector(NUM_LEDS     - 1 downto 0);
    clk_half_ns : in  natural := CLK_HALF_NS_INIT
  );
end entity;

architecture rtl of sim_wrapper is
  signal clk : std_logic := '0';
begin

  -- Free-running clock whose half-period (ns) equals clk_half_ns.
  -- The wait-for expression re-evaluates on each iteration, so writing
  -- a new value takes effect within one half-period.
  clk_proc : process
  begin
    clk <= '0';
    wait for clk_half_ns * 1 ns;
    clk <= '1';
    wait for clk_half_ns * 1 ns;
  end process;

  uut : entity work.{toplevel}
    generic map (
      NUM_SWITCHES => NUM_SWITCHES,
      NUM_BUTTONS  => NUM_BUTTONS,
      NUM_LEDS     => NUM_LEDS,
      COUNTER_BITS => COUNTER_BITS
    )
    port map (
      clk => clk,
      sw  => sw,
      btn => btn,
      led => led
    );

end architecture;
