-- sim_wrapper_template.vhd
-- Generated by sim_bridge.py: placeholders are replaced with actual values
-- before this file is analysed.
--
-- Driving the clock from VHDL eliminates all per-half-period Python-to-
-- simulator GPI callbacks, cutting simulator step time ~10x.
--
-- clk_half_ns controls the virtual clock frequency at runtime.
-- sim_testbench.py writes dut.clk_half_ns.value whenever the panel's
-- [-]/[+] buttons are pressed; the VHDL process picks up the new value
-- on the next half-cycle, identical to the prior Python _dynamic_clock
-- behaviour.
--
-- The duty_* placeholders carry the U9 duty integrator, spliced in only when
-- the run's measurement mode is Full (sim/duty/*.vhd.frag).  In the Off and
-- Color-only modes they all expand to nothing and the monitored outputs are
-- wired straight through, so the generated file is byte-identical to the
-- pre-U9 wrapper and costs exactly nothing.

library ieee;
use ieee.std_logic_1164.all;
{numeric_use}
entity sim_wrapper is
  generic (
    NUM_SWITCHES     : positive := 4;
    NUM_BUTTONS      : positive := 4;
    NUM_LEDS         : positive := 4;
{seg_generic}{rgb_generic}    COUNTER_BITS     : positive := 24;
    CLK_HALF_NS_INIT : positive := 20
  );
  port (
    sw          : in  std_logic_vector(NUM_SWITCHES - 1 downto 0);
    btn         : in  std_logic_vector(NUM_BUTTONS  - 1 downto 0);
    led         : out std_logic_vector(NUM_LEDS     - 1 downto 0);
{seg_port}{duty_ports}    clk_half_ns : in  natural := CLK_HALF_NS_INIT
  );
end entity;

architecture rtl of sim_wrapper is
  signal clk : std_logic := '0';
{duty_decls}begin

  -- Free-running clock whose half-period (ns) equals clk_half_ns.
  -- The wait-for expression re-evaluates on each iteration, so writing
  -- a new value takes effect within one half-period.
  clk_proc : process
  begin
    clk <= '0';
    wait for clk_half_ns * 1 ns;
    clk <= '1';
    wait for clk_half_ns * 1 ns;
  end process;
{duty_body}
  uut : entity work.{toplevel}
    generic map (
      NUM_SWITCHES => NUM_SWITCHES,
      NUM_BUTTONS  => NUM_BUTTONS,
      NUM_LEDS     => NUM_LEDS,
{seg_generic_map}{rgb_generic_map}      COUNTER_BITS => COUNTER_BITS
    )
    port map (
      clk => clk,
      sw  => sw,
      btn => btn,
{seg_port_map}      led => {led_sig}
    );

end architecture;
