-- ===========================================================================
-- mx65_irq_counter_7seg.vhd  -  single-file 6502 embedded-core system
--
-- Interrupt-driven variant of the walking counter: a vendored mx65 6502 CPU core
-- (below, verbatim, MIT) + ROM + RAM + memory-mapped IO + a top that wires the
-- prescaler tick to the CPU's (active-low) IRQ line.
--
-- The firmware (firmware/mx65_irq_counter_7seg.s) enables interrupts and idles; the
-- ISR runs once per tick -- acknowledging it by reading $E010 -- and does the same
-- work as the polled design: a one-hot LED bounces across the LEDs while a decimal
-- odometer advances; btn(0) reverses both directions, btn(1) is a lamp test, and
-- each active switch steps faster.  Behavior matches hdl/mx65_walking_counter_7seg.
-- See docs/embedded_core_system_plan.md.
--
-- Generated by scripts/gen_embedded_core.py -- do not edit by hand.
-- Regenerate from the vendored CPU core, firmware/mx65_irq_counter_7seg.bin,
-- and the system spec systems/mx65_irq_counter_7seg.toml.
-- ===========================================================================

-------------------------------------------------------------------------------
-- Vendored verbatim from the MX65 project - do not edit this file by hand.
--
--   Source : https://github.com/Steve-Teal/mx65  (file: mx65.vhd)
--   Commit : d65d81d4f8031e194bd8410133b9036db7e58794
--   License: MIT (Copyright (c) 2022 Steve Teal)
--
-- Unmodified copy of the upstream 6502 core, used as the CPU for the
-- simulator's embedded-core systems (see docs/embedded_core_system_plan.md).
-- To update, re-vendor from a new pinned commit; never hand-edit the core text.
--
-- MIT License
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-- SOFTWARE.
-------------------------------------------------------------------------------

-------------------------------------------------
--
-- MX65 - 6502 processor core
-- This file is part of the MX65 Project
-- Copyright (c) 2022 Steve Teal
--
-------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all; 
	
entity mx65 is
  port (
	clock	: in std_logic;
	reset	: in std_logic;	  
	ce		: in std_logic;
	data_in	: in std_logic_vector(7 downto 0);
	data_out: out std_logic_vector(7 downto 0);
	address	: out std_logic_vector(15 downto 0);
	rw		: out std_logic;
	sync	: out std_logic;
	nmi		: in std_logic;
	irq		: in std_logic);
end entity;

architecture rtl of mx65 is

	signal a : std_logic_vector(7 downto 0);
	signal x : std_logic_vector(7 downto 0);
	signal y : std_logic_vector(7 downto 0);
	signal s : std_logic_vector(7 downto 0);
	signal dl : std_logic_vector(7 downto 0);
	signal ir : std_logic_vector(7 downto 0);
	signal pcl : std_logic_vector(7 downto 0);
	signal pch : std_logic_vector(7 downto 0);
	signal adl : std_logic_vector(7 downto 0);
	signal adh : std_logic_vector(7 downto 0);
	signal c : std_logic;
	signal z : std_logic;
	signal n : std_logic;
	signal v : std_logic;
	signal d : std_logic;
	signal i : std_logic;	
	signal b : std_logic;
	
	type state_type is (T0,T1,BRK2_JSR3,PHA2,PHP2_BRK4,PLX2_RTX2,JSR2,JMPABS2_JSR5,ABS2,
			BR2,IZX2_ZPX2,IZY2_IZX3_JMPIND3,ZPY2,ABX2,ABY2,TREAD,TWRITE,BRK3_JSR4,PLA3,
			PLP3,RTS3_RTI4,RTI3,BR3,IZY3,RTS4_RTI5,JMPIND4,IZX4,BRK5,BRK6,RTS5,TFIX,TMOD);
	
	type control_type is record 
		src_a,src_x,src_y,src_s,src_dl,src_pcl,src_pch,src_p,dst_a,dst_x,dst_y,dst_dl,
        dst_adl,dst_adh,dst_pcl,dst_pch,dst_s,load_dl,load_adl,load_adh,load_pcl,
        load_pch,load_nv,load_czid,update_c,update_z,update_n,update_v,clcsec,clisei,
        cldsed,inc_pc,alu_fn0,alu_fn1,force_carry,carry_enable,alu_invert,alu_dl,alu_sr,
        bcd_add,bcd_sub,write_enable : std_logic;		
		end record;
			
	type decode_type is record
		brk,jsr,rti,rts,php,plp,pha,pla,bita,jmpabs,jmpind,sty,ldy,cpy,cpx,dey,tya,tay,clv,
		iny,inx,clcsec,clisei,cldsed,ora,anda,eor,adc,sta,lda,cmp,sbc,asl,rotl,lsr,rotr,stx,
		sta_stx_sty,ldx,dec,inc,a_shift,txa,txs,tax,tsx,dex,index_y,zp,ab,zp_index,ab_index,
		indirect_x,indirect_y,single_byte,br,read_mod_write : std_logic;
		
		end record;
		
	signal addr_pc, addr_ad, addr_s : std_logic_vector(15 downto 0);
	signal state : state_type;
	signal control : control_type;
	signal decode : decode_type;
	signal pc_add_1 : std_logic_vector(15 downto 0);
	signal flag_mux : std_logic;
	signal carry_in : std_logic;
	signal half_carry : std_logic;
	signal full_carry : std_logic;
	signal carry_out : std_logic;
	signal carry_reg : std_logic; -- Registered ALU carry out
	signal data_mux : std_logic_vector(7 downto 0);
	signal alu_a    : unsigned(7 downto 0);
	signal alu_b    : unsigned(7 downto 0);
	signal adder_hi : unsigned(4 downto 0);
	signal adder_lo : unsigned(4 downto 0);
	signal alu_out  : unsigned(7 downto 0);
	signal bcd_fix  : unsigned(7 downto 0);	
	signal brk_vect : std_logic_vector(14 downto 0);
	signal reset_reg : std_logic;
	signal nmi_reg : std_logic;
	signal nmi_mask : std_logic;	  
	signal nmi_ready : std_logic;
	signal irq_ready : std_logic;
	signal t0_irq_nmi : std_logic;	 
	signal inhibit_pcinc : std_logic;
	signal enable : std_logic;

begin

	data_mux <= (a or (7 downto 0 => not control.src_a)) and
				(x or (7 downto 0 => not control.src_x)) and
				(y or (7 downto 0 => not control.src_y)) and	 
				(s or (7 downto 0 => not control.src_s)) and	 
				(dl or (7 downto 0 => not control.src_dl)) and
				(pcl or (7 downto 0 => not control.src_pcl)) and
				(pch or (7 downto 0 => not control.src_pch)) and
				( n & v & '1' & b & d & i & z & c or (7 downto 0 => not control.src_p));

	data_out <= data_mux;  
	enable <= ce;
	
	brk_vect(14 downto 2) <= "1111111111111";
	brk_vect(1) <= not nmi_reg;
	brk_vect(0) <= not reset_reg;
	
	rw <= not control.write_enable;
	
	sync <='1' when state = T0 else '0';   	
	
	nmi_ready <= not (reset_reg or nmi or nmi_mask);  
	irq_ready <= not (reset_reg or irq or i);
	t0_irq_nmi <= (nmi_ready or irq_ready) when state = T0 else '0';  
	inhibit_pcinc <= t0_irq_nmi or not b;

	process (clock, reset, enable, state)
	begin
		if reset='1' then
			reset_reg <= '1';
			b <= '1';
			nmi_reg <= '0';
			nmi_mask <= '0';
		elsif rising_edge(clock) then
			if enable = '1' and (state=T0 or state=BRK6) then
				b <= not t0_irq_nmi;
				nmi_reg <= nmi_ready;
				nmi_mask <= nmi_ready or (nmi_mask and not nmi);   
				if state=BRK6 then
					reset_reg <= '0';
				end if;
			end if;
		end if;
	end process;
		
	process (clock, reset, enable, state) begin
		if reset = '1' then
			ir <= X"00";	 	
        elsif rising_edge(clock) then
			if enable='1' and state=T0 then
				if reset_reg='1' or t0_irq_nmi='1' then
					ir <= X"00";
				else
					ir <= data_in;
				end if;
			end if;
        end if;
    end process;
	
	with ir(7 downto 6) select flag_mux <=
		n when "00",
		v when "01",
		c when "10",
		z when "11",
		'0' when others;
		
	addr_pc <= pch & pcl;
	addr_ad <= adh & adl;
	addr_s <= X"01" & s;
	
	
	process(clock, reset, enable)
	begin
		if reset = '1' then
			carry_reg <= '0';
		elsif rising_edge(clock) then
			if enable='1' then
				carry_reg <= carry_out;
			end if;
		end if;
	end	process;
	
	---------------------------------------
	--
	-- Instruction Decoder
	--
	---------------------------------------
	
	process(ir) begin
		decode <= (others=>'0');
		
		decode.index_y <= ir(2) nand (ir(1) nand (ir(7) and not ir(6)));
		decode.zp <= ir(2) and (ir(3) nor ir(4));
		decode.ab <= ir(2) and ir(3) and not ir(4);
		decode.zp_index <= ir(2) and ir(4) and not ir(3);
		decode.ab_index <= (ir(2) or ir(0)) and ir(3) and ir(4);
		decode.indirect_x <= ir(0) and not (ir(2) or ir(3) or ir(4));
		decode.indirect_y <= ir(0) and ir(4) and (ir(2) nor ir(3));	
		decode.single_byte <= ir(3) and (ir(0) nor ir(2));		
		decode.br <= ir(4) and not (ir(3) or ir(2) or ir(1) or ir(0));
		decode.sta_stx_sty <= ir(7) and (ir(6) nor ir(5));
		
		if ir(1 downto 0)="00" then
			case(ir(7 downto 2))is
				when "000000" => decode.brk <= '1';
				when "001000" => decode.jsr <= '1';
				when "010000" => decode.rti <= '1';
				when "011000" => decode.rts <= '1';
				when "000010" => decode.php <= '1';
				when "001010" => decode.plp <= '1';
				when "010010" => decode.pha <= '1';
				when "011010" => decode.pla <= '1';				
				when "100010" => decode.dey <= '1';
				when "100110" => decode.tya <= '1';
				when "101010" => decode.tay <= '1';
				when "101110" => decode.clv <= '1';
				when "110010" => decode.iny <= '1';
				when "111010" => decode.inx <= '1';
				when "010011" => decode.jmpabs <= '1';
				when "011011" => decode.jmpind <= '1';			
				when "100001"|"100011"|"100101"|"100111" => decode.sty <='1';
				when "001001"|"001011" => decode.bita <= '1';						
				when "000110"|"001110" => decode.clcsec <= '1';
				when "010110"|"011110" => decode.clisei <= '1';
				when "110110"|"111110" => decode.cldsed <= '1';
				when "101000"|"101001"|"101011"|"101101"|"101111" => decode.ldy <= '1';
				when "110000"|"110001"|"110011" => decode.cpy <= '1';	
				when "111000"|"111001"|"111011" => decode.cpx <= '1';				
				when others => null;
			end case;
		end if;
		
		if ir(0)='1' then
			case(ir(7 downto 5))is
				when "000" => decode.ora <= '1';
				when "001" => decode.anda <= '1';
				when "010" => decode.eor <= '1';
				when "011" => decode.adc <= '1';
				when "100" => decode.sta <= '1';
				when "101" => decode.lda <= '1';
				when "110" => decode.cmp <= '1';
				when "111" => decode.sbc <= '1';
				when others => null;				
			end case;					
		end if;
		
		if ir(1)='1' then
			case(ir(7 downto 5)) is
				when "000" => decode.asl <= '1';
				when "001" => decode.rotl <= '1';
				when "010" => decode.lsr <= '1';
				when "011" => decode.rotr <= '1';
				when "100" => decode.stx <= '1';
				when "101" => decode.ldx <= '1';
				when "110" => decode.dec <= '1';
				when "111" => decode.inc <= '1';
				when others => null;				
			end case;
			decode.read_mod_write <= ir(6) or not ir(7);			
		end if;
		
		if ir(3 downto 1)="101" then
			case(ir(7 downto 4)) is
				when "0000"|"0010"|"0100"|"0110" => decode.a_shift <= '1';
				when "1000" => decode.txa <= '1';
				when "1001" => decode.txs <= '1';
				when "1010" => decode.tax <= '1';
				when "1011" => decode.tsx <= '1';
				when "1100" => decode.dex <= '1';
				when others => null;
			end case;
		end if;
		
	end process;
	
	---------------------------------------
	--
	-- State machine
	--
	---------------------------------------
	
	process (reset, clock, enable) begin
		if reset='1' then
			state <= T0;
		elsif rising_edge(clock) then
			if enable='1' then
				case state is
					when T0 => state <= T1;
					when T1 =>
						if decode.brk = '1' then
							state <= BRK2_JSR3;
						elsif decode.pha = '1' then
							state <= PHA2;
						elsif decode.php = '1' then
							state <= PHP2_BRK4;
						elsif decode.plp = '1' or decode.pla = '1' or decode.rts = '1' or decode.rti = '1' then
							state <= PLX2_RTX2;
						elsif decode.jsr = '1' then
							state <= JSR2;
						elsif decode.jmpabs = '1' then
							state <= JMPABS2_JSR5;
						elsif decode.ab = '1' then
							state <= ABS2;
						elsif decode.br = '1' and flag_mux = ir(5) then
							state <= BR2;
						elsif decode.zp_index = '1' and decode.index_y = '1' then
							state <= ZPY2;
						elsif decode.zp_index = '1' or decode.indirect_x = '1' then
							state <= IZX2_ZPX2;
						elsif decode.ab_index = '1' and decode.index_y = '1' then
							state <= ABY2;
						elsif decode.ab_index = '1' then
							state <= ABX2;
						elsif decode.indirect_y = '1' then
							state <= IZY2_IZX3_JMPIND3;
						elsif decode.zp = '1' and decode.sta_stx_sty = '1' then
							state <= TWRITE;
						elsif decode.zp = '1' then
							state <= TREAD;	
						else
							state <= T0;
						end if;
					when BRK2_JSR3 => state <= BRK3_JSR4;			
					when PHP2_BRK4 =>
						if decode.brk = '1' then
							state <= BRK5;
						else
							state <= T0;
						end if;
					when PLX2_RTX2 =>
						if decode.pla = '1' then
							state <= PLA3;
						elsif decode.plp = '1' then
							state <= PLP3;
						elsif decode.rti = '1' then
							state <= RTI3;
						else
							state <= RTS3_RTI4;
						end if;
					when JSR2 => state <= BRK2_JSR3;				
					when ABS2|IZX2_ZPX2 => 
						if decode.jmpind = '1' or decode.indirect_x = '1' then
							state <= IZY2_IZX3_JMPIND3;
						elsif decode.sta_stx_sty = '1' then
							state <= TWRITE;
						else
							state <= TREAD;
						end if;
					when BR2 =>
						if dl(7) = carry_out then
							state <= T0;
						else
							state <= BR3;
						end if;
					when IZY2_IZX3_JMPIND3 =>
						if decode.indirect_x = '1' then
							state <= IZX4;
						elsif decode.indirect_y = '1' then
							state <= IZY3;
						else
							state <= JMPIND4;
						end if;
					when ZPY2|IZX4 =>
						if decode.sta_stx_sty = '1' then
							state <= TWRITE;
						else
							state <= TREAD;
						end if;
					when ABX2|ABY2|IZY3 => state <= TFIX;
					when TREAD =>
						if decode.read_mod_write = '1' then
							state <= TMOD;
						else
							state <= T0;
						end if;				
					when BRK3_JSR4 =>
						if decode.brk = '1' then
							state <= PHP2_BRK4;
						else
							state <= JMPABS2_JSR5;
						end if;			
					when RTS3_RTI4 => state <= RTS4_RTI5;
					when RTI3 => state <= RTS3_RTI4;
					when RTS4_RTI5 =>
						if decode.rts = '1' then
							state <= RTS5;
						else
							state <= T0;
						end if;				
					when BRK5 => state <= BRK6;							
					when TFIX =>
						if decode.sta_stx_sty = '1' then
							state <= TWRITE;
						elsif decode.read_mod_write = '1' or carry_reg = '1' then
							state <= TREAD;
						else
							state <= T0;
						end if;
					when TMOD => state <= TWRITE;
					when TWRITE|PLA3|PLP3|BR3|JMPIND4|BRK6|RTS5|JMPABS2_JSR5|PHA2 => state <= T0;
				end case;		
			end if;
		end if;
	end process;
	
	---------------------------------------
	--
	-- Control signal logic and address mux
	--
	---------------------------------------
	
	process (state, decode, carry_reg, addr_pc, addr_s, addr_ad, d, data_mux, adl, adh, s, reset_reg, brk_vect)
	begin
		control <= (others => '0');				
		case state is
			when T0 =>		
				control.inc_pc <= '1';
				-- Source
				control.src_a <= decode.tay or decode.tax or decode.cmp or decode.a_shift or decode.ora
					or decode.anda or decode.eor or decode.bita or decode.adc or decode.sbc;
				control.src_x <= decode.inx or decode.dex or decode.txa or decode.txs or decode.cpx;
				control.src_y <= decode.iny or decode.dey or decode.tya or decode.cpy;
				control.src_dl <= decode.pla or decode.lda or decode.ldy or (decode.ldx and not decode.tsx); 
				control.src_s <= decode.tsx;
				-- Destination
				control.dst_a <= decode.pla or decode.a_shift or decode.txa or decode.tya or decode.ora
					or decode.anda or decode.eor or decode.adc or decode.sbc or decode.lda;
				control.dst_x <= decode.inx or decode.dex or decode.tax or decode.tsx or decode.ldx;
				control.dst_y <= decode.iny or decode.dey or decode.tay or decode.ldy;
				control.dst_s <= decode.txs;
				-- Function
				control.bcd_add <= decode.adc and d;
				control.bcd_sub <= decode.sbc and d;
				control.alu_fn0 <= decode.ora or decode.eor;
				control.alu_fn1 <= decode.anda or decode.bita or decode.eor;	
				control.force_carry <= decode.iny or decode.inx or decode.cmp or decode.cpx or decode.cpy;
				control.carry_enable <= decode.adc or decode.sbc or decode.rotl or decode.rotr;
				control.alu_invert <= decode.dey or decode.dex or decode.sbc or decode.cmp or decode.cpx or decode.cpy;
				control.alu_dl <= decode.ora or decode.anda or decode.eor or decode.bita or decode.adc or
					decode.sbc or decode.cmp or decode.cpx or decode.cpy or decode.asl or decode.rotl;
				control.alu_sr <= decode.lsr or decode.rotr;
				-- Flags   
				
				control.update_n <= decode.pla or decode.a_shift or decode.txa or decode.tya or decode.ora
					or decode.anda or decode.eor or decode.adc or decode.sbc or decode.lda or decode.inx or
					decode.dex or decode.tax or decode.cpx or decode.tsx or decode.iny or decode.ldx or
					decode.dey or decode.tay or decode.ldy or decode.cmp or decode.cpx or decode.cpy;	   
				
				control.update_z <= decode.pla or decode.a_shift or decode.txa or decode.tya or decode.ora
					or decode.anda or decode.eor or decode.adc or decode.sbc or decode.lda or decode.inx or
					decode.dex or decode.tax or decode.cpx or decode.tsx or decode.iny or decode.ldx or
					decode.dey or decode.tay or decode.ldy or decode.cmp or decode.cpx or decode.cpy or decode.bita;   
				
				control.update_c <= decode.adc or decode.sbc or decode.cmp or decode.cpx or decode.cpy or decode.a_shift;
				control.update_v <= decode.adc or decode.sbc or decode.clv;
				control.clcsec <= decode.clcsec;
				control.clisei <= decode.clisei;
				control.cldsed <= decode.cldsed;
				-- Address
				address <= addr_pc;	 
				alu_a <= unsigned(data_mux);
			when T1 => -- Single Byte: DL = A   Multi Byte: DL,ADL = [PC++], ADH = 0				
				control.dst_dl <= decode.single_byte;
				control.src_a <= decode.single_byte;				
				control.load_dl <= not decode.single_byte;
				control.load_adl <= not decode.single_byte;
				control.dst_adh <= not decode.single_byte;
				control.force_carry <= not decode.single_byte; -- ALU output = 0 (0xFF + 1)
				control.inc_pc <= not decode.single_byte;								
				address <= addr_pc;		 
				alu_a <= unsigned(data_mux);					
			when BRK2_JSR3 => -- [S--] = PCH
				control.write_enable <= not reset_reg;
				control.src_pch <= '1';
				control.alu_invert <= '1'; 
				control.dst_s <= '1';
				address <= addr_s;	
				alu_a <= unsigned(s);
			when PHA2 => -- [S--] = A
				control.write_enable <= '1';
				control.src_a <= '1';
				control.alu_invert <= '1';
				control.dst_s <= '1';
				address <= addr_s;		
				alu_a <= unsigned(s);
			when PHP2_BRK4 => -- [S--] = P
				control.write_enable <= not reset_reg;
				control.src_p <= '1';
				control.alu_invert <= '1';
				control.dst_s <= '1';
				address <= addr_s; 
				alu_a <= unsigned(s);
			when PLX2_RTX2 => -- [S++]
				control.force_carry <= '1';
				control.dst_s <= '1';
				address <= addr_s;
				alu_a <= unsigned(s);
			when JSR2 => -- [S]
				address <= addr_s;	
				alu_a <= unsigned(data_mux);
			when JMPABS2_JSR5 => -- PCH=[PC]; PCL=ADL
				control.load_pch <= '1';				
				control.dst_pcl <= '1';
				address <= addr_pc;	
				alu_a <= unsigned(adl);
			when ABS2 => -- ADH = [PC++]
				control.load_adh <= '1';
				control.inc_pc <= '1';
				address <= addr_pc;	  
				alu_a <= unsigned(data_mux);
			when BR2 => -- PCL=PCL+DL; [PC]
				control.src_pcl <= '1';
				control.alu_dl <= '1';
				control.dst_pcl <= '1';
				address <= addr_pc;	
				alu_a <= unsigned(data_mux);
			when IZX2_ZPX2 => -- ADL=X+DL; [AD]
				control.src_x <= '1';
				control.alu_dl <= '1';
				control.dst_adl <= '1';				
				address <= addr_ad;	
				alu_a <= unsigned(data_mux);
			when IZY2_IZX3_JMPIND3 => -- DL=[ADL++]
				control.load_dl <= '1';
				control.dst_adl <= '1';
				control.force_carry <= '1';	
				address <= addr_ad;	
				alu_a <= unsigned(adl);
			when ZPY2 => -- ADL=Y+DL; [AD]
				control.src_y <= '1';
				control.alu_dl <= '1';
				control.dst_adl <= '1';
				address <= addr_ad;	 
				alu_a <= unsigned(data_mux);
			when ABX2 => -- ADH=[PC++]; ADL=X+DL
				control.src_x <= '1';
				control.dst_adl <= '1';
				control.alu_dl <= '1';
				control.load_adh <= '1';
				control.inc_pc <= '1';
				address <= addr_pc;	 
				alu_a <= unsigned(data_mux);
			when ABY2 => -- ADH=[PC++]; ADL=Y+DL
				control.src_y <= '1';
				control.dst_adl <= '1';
				control.alu_dl <= '1';
				control.load_adh <= '1';
				control.inc_pc <= '1';
				address <= addr_pc;	
				alu_a <= unsigned(data_mux);
			when TREAD => -- DL = [AD]
				control.load_dl <= '1';
				control.load_nv <= decode.bita;
				address <= addr_ad;	
				alu_a <= unsigned(data_mux);
			when TWRITE => -- [AD] = reg
				control.src_a <= decode.sta;
				control.src_x <= decode.stx;
				control.src_y <= decode.sty;
				control.src_dl <= decode.read_mod_write;
				control.write_enable <= '1';
				address <= addr_ad;	
				alu_a <= unsigned(data_mux);
			when BRK3_JSR4 => -- [S--] = PCL
				control.write_enable <= not reset_reg;
				control.alu_invert <= '1';
				control.dst_s <= '1';
				control.src_pcl <= '1';
				address <= addr_s; 
				alu_a <= unsigned(s);
			when PLA3 => -- DL=[S]
				control.load_dl <= '1';
				address <= addr_s;
				alu_a <= unsigned(data_mux);
			when PLP3 => -- P=[S]
				control.load_czid <= '1';
				control.load_nv <= '1';
				address <= addr_s; 
				alu_a <= unsigned(data_mux);
			when RTS3_RTI4 => -- PCL=[S++]
				control.force_carry <= '1';
				control.dst_s <= '1';
				control.load_pcl <= '1';
				address <= addr_s;	
				alu_a <= unsigned(s);
			when RTI3 => -- P=[S++]
				control.force_carry <= '1';
				control.dst_s <= '1';
				control.load_czid <= '1';
				control.load_nv <= '1';
				address <= addr_s;
				alu_a <= unsigned(s);
			when BR3 =>	-- if carry_reg) PCH++; else PCH--;
				control.force_carry <= carry_reg;
				control.alu_invert <= not carry_reg;				
				control.src_pch <= '1';
				control.dst_pch <= '1';
				address <= addr_pc;	
				alu_a <= unsigned(data_mux);
			when IZY3 => -- ADH=[AD]; ADL=DL+Y
				control.src_y <= '1';
				control.dst_adl <= '1';
				control.alu_dl <= '1';
				control.load_adh <= '1';
				address <= addr_ad;
				alu_a <= unsigned(data_mux);
			when RTS4_RTI5 => -- PCH=[S]
				control.load_pch <= '1';
				address <= addr_s;
				alu_a <= unsigned(data_mux);
			when JMPIND4 => -- PCH=[AD]; PCL=DL
				control.load_pch <= '1';
				control.src_dl <= '1';
				control.dst_pcl <= '1';
				address <= addr_ad;	
				alu_a <= unsigned(data_mux);
			when IZX4 => -- ADH = [AD]; ADL=DL
				control.load_adh <= '1';
				control.src_dl <= '1';
				control.dst_adl <= '1';
				address <= addr_ad;
				alu_a <= unsigned(data_mux);
			when BRK5 => -- PCL = [VECTOR_LOW]
				control.load_pcl <= '1';
				address <= brk_vect & '0'; 
				alu_a <= unsigned(data_mux);
			when BRK6 => -- PCH = [VECTOR_HIGH]
				control.load_pch <= '1';
				address <= brk_vect & '1';
				alu_a <= unsigned(data_mux);
			when RTS5 => -- [PC++]
				control.inc_pc <= '1';
				address <= addr_pc;
				alu_a <= unsigned(data_mux);
			when TFIX => -- DL = [AD], page boundry crossed: ADH++
				control.dst_adh <= carry_reg;				
				control.force_carry <= '1';
				control.load_dl <= '1';
				address <= addr_ad;
				alu_a <= unsigned(adh);
			when TMOD =>	
				control.write_enable <= '1';
				control.src_dl <= '1';
				control.dst_dl <= '1';
				control.alu_sr <= decode.rotr or decode.lsr;
				control.alu_dl <= decode.rotl or decode.asl;
				control.carry_enable <= decode.rotr or decode.rotl;
				control.force_carry <= decode.inc;
				control.alu_invert <= decode.dec;
				control.update_z <= '1';
				control.update_n <= '1';
				control.update_c <= decode.rotl or decode.asl or decode.rotr or decode.lsr;
				address <= addr_ad;	 
				alu_a <= unsigned(data_mux);
		end case;
	end process;

	---------------------------------------
	--
	-- DL Register
	--
	---------------------------------------		
	
	process(clock, reset, enable)
	begin
		if reset = '1' then
			dl <= X"00";	
		elsif rising_edge(clock) then
			if enable='1' then
				if control.load_dl = '1' then
					dl <= data_in;
				elsif control.dst_dl = '1' then
					dl <= std_logic_vector(alu_out);
				end if;
			end if;
		end if;
	end process;
	
	
	---------------------------------------
	--
	-- ADL Register
	--
	---------------------------------------	

	process(clock, reset, enable)
	begin
		if reset = '1' then
			adl <= (others=>'1');
		elsif rising_edge(clock) then
			if enable='1' then
				if control.load_adl = '1' then
					adl <= data_in;
				elsif control.dst_adl = '1' then
					adl <= std_logic_vector(alu_out);
				end if;
			end if;
		end if;
	end process;


	---------------------------------------
	--
	-- ADH Register
	--
	---------------------------------------

	process(clock, reset, enable)
	begin
		if reset = '1' then
			adh <= (others=>'0');
		elsif rising_edge(clock) then
			if enable='1' then	
				if control.load_adh = '1' then
					adh <= data_in;	 
				elsif control.dst_adh = '1' then
					adh <= std_logic_vector(alu_out);
				end if;
			end if;
		end if;		
	end process;
	
	---------------------------------------
	--
	-- A,X,Y,S Registers
	--
	---------------------------------------

	process(clock, reset, enable)
	begin
		if reset = '1' then
			a <= (others=>'0');
			x <= (others=>'0');
			y <= (others=>'0');	   
			s <= (others=>'0');
		elsif rising_edge(clock) then
			if enable='1' then
				if control.dst_a = '1' then
					a(3 downto 0) <= std_logic_vector(alu_out(3 downto 0) + bcd_fix(3 downto 0));
					a(7 downto 4) <= std_logic_vector(alu_out(7 downto 4) + bcd_fix(7 downto 4));
				end if;
				if control.dst_x = '1' then
					x <= std_logic_vector(alu_out);
				end if;
				if control.dst_y = '1' then
					y <= std_logic_vector(alu_out);
				end if;
				if control.dst_s = '1' then
					s <= std_logic_vector(alu_out);
				end if;
			end if;
		end if;
	end process;
	
	---------------------------------------
	--
	-- PCH, PCL registers
	--
	---------------------------------------
	
	process(clock, reset, addr_pc, enable)
	begin
		pc_add_1 <= std_logic_vector(unsigned(addr_pc) + 1);
		if reset = '1' then
			pcl <= (others=>'0');
			pch <= (others=>'0');
		elsif rising_edge(clock) then
			if enable='1' then
				if control.inc_pc = '1' and inhibit_pcinc = '0' then
					pcl <= pc_add_1(7 downto 0);
					pch <= pc_add_1(15 downto 8);
				else
					if control.load_pcl = '1' then
						pcl <= data_in;
					elsif control.dst_pcl = '1' then
						pcl <= std_logic_vector(alu_out);
					end if;
					if control.load_pch = '1' then
						pch <= data_in;
					elsif control.dst_pch = '1' then
						pch <= std_logic_vector(alu_out);
					end if;
				end if;
			end if;
		end if;
	end process;

	---------------------------------------
	--
	-- Carry Flag
	--
	---------------------------------------
    
	process(clock, reset, enable)
	begin
		if reset = '1' then
			c <= '0';			
		elsif rising_edge(clock) then
			if enable='1' then
				if control.load_czid = '1' then
					c <= data_in(0);
				elsif control.update_c = '1' then
					c <= carry_out;
				elsif control.clcsec = '1' then
					c <= ir(5);
				end if;
			end if;
		end if;
	end process;
	
	---------------------------------------
	--
	-- Zero Flag
	--
	---------------------------------------
    
	process(clock, reset, enable)
	begin	
		if reset = '1' then
			z <= '0';
		elsif rising_edge(clock) then
			if enable='1' then
				if control.load_czid = '1' then
					z <= data_in(1);
				elsif control.update_z = '1' then		
					if alu_out = X"00" then
						z <= '1';
					else
						z <= '0';
					end if;
				end if;			
			end if;
		end if;
	end process;
	
	---------------------------------------
	--
	-- Interrupt Disable Flag
	--
	---------------------------------------
    
	process(clock, reset, enable)
	begin	
		if reset = '1' then
			i <= '1'; -- Interrupts disabled
		elsif rising_edge(clock) then
			if enable='1' then
				if control.load_czid = '1' then
					i <= data_in(2);
				elsif control.clisei = '1' then
					i <= ir(5);
				elsif state = BRK6 then	
					i <= '1';
				end if;
			end if;
		end if;
	end process;
	
	---------------------------------------
	--
	-- Decimal Flag
	--
	---------------------------------------
    
	process(clock, reset, enable)
	begin	
		if reset = '1' then
			d <= '0'; 
		elsif rising_edge(clock) then
			if enable='1' then	
				if control.load_czid = '1' then
					d <= data_in(3);
				elsif control.cldsed = '1' then
					d <= ir(5);
				end if;
			end if;
		end if;
	end process;
	
	---------------------------------------
	--
	-- Overflow Flag
	--
	---------------------------------------
    
	process(clock, reset, enable)
	begin	
		if reset = '1' then
			v <= '0'; 
		elsif rising_edge(clock) then
			if enable='1' then
				if control.load_nv = '1' then
					v <= data_in(6);
				elsif control.update_v = '1' then
					-- Overflow occurs when the ALU input signs match and the output sign does not
					if alu_a(7) /= adder_hi(3) and alu_b(7) /= adder_hi(3) then
						v <= '1';
					else
						v <= '0';
					end if;			
				end if;
			end if;
		end if;
	end process;
	
	---------------------------------------
	--
	-- Negative Flag
	--
	---------------------------------------
    
	process(clock, reset, enable)
	begin	
		if reset = '1' then
			n <= '0'; 	
		elsif rising_edge(clock) then
			if enable='1' then
				if control.load_nv = '1' then
					n <= data_in(7);
				elsif control.update_n = '1' then
					n <= alu_out(7);
				end if;
			end if;
		end if;
	end process;
	
	---------------------------------------
	--
	-- ALU B input
	--
	---------------------------------------	
	
	process(control, dl, enable)
	begin
		if control.alu_dl = '1' then
			if control.alu_invert = '1' then
				alu_b <= unsigned(not dl);
			else
				alu_b <= unsigned(dl);
			end if;
		else
			if control.alu_invert = '1' then
				alu_b <= X"FF";
			else
				alu_b <= X"00";
			end if;
		end if;
	end process;

	---------------------------------------
	--
	-- ALU 
	--
	---------------------------------------	

	carry_in <= control.force_carry or (control.carry_enable and c);
	adder_lo <= ('0' & alu_a(3 downto 0)) + ('0' & alu_b(3 downto 0)) + ("0000" & carry_in);
	adder_hi <= ('0' & alu_a(7 downto 4)) + ('0' & alu_b(7 downto 4)) + ("0000" & half_carry);
	half_carry <= adder_lo(4) or (control.bcd_add and adder_lo(3) and (adder_lo(2) or adder_lo(1)));
	full_carry <= adder_hi(4) or (control.bcd_add and adder_hi(3) and (adder_hi(2) or adder_hi(1)));
	
	process(control,carry_in,alu_a,alu_b,adder_hi,adder_lo,full_carry)
	begin
		if control.alu_sr = '1' then
			alu_out <= (carry_in & alu_a(7 downto 1));
			carry_out <= alu_a(0);
		else
			if control.alu_fn1 = '0' and control.alu_fn0 = '0' then
				alu_out <= (adder_hi(3 downto 0) & adder_lo(3 downto 0));
			elsif control.alu_fn1 = '0' and control.alu_fn0 = '1' then
				alu_out <= alu_a or alu_b;
			elsif control.alu_fn1 = '1' and control.alu_fn0 = '0' then
				alu_out <= alu_a and alu_b;
			else
				alu_out <= alu_a xor alu_b;
			end if;
			carry_out <= full_carry;
		end if;
	end process;
	

	---------------------------------------
	--
	-- BCD FiX 
	--
	---------------------------------------		
	
	bcd_fix(0) <= '0';
	bcd_fix(1) <= bcd_fix(2) or bcd_fix(3);
	bcd_fix(2) <= control.bcd_add and half_carry;
	bcd_fix(3) <= control.bcd_sub and not half_carry;
	bcd_fix(4) <= '0';
	bcd_fix(5) <= bcd_fix(6) or bcd_fix(7);
	bcd_fix(6) <= control.bcd_add and full_carry;
	bcd_fix(7) <= control.bcd_sub and not full_carry;
		
end architecture;

-- End of file


-- ===========================================================================
-- System blocks (generated).  The mx65 core above is vendored verbatim.
-- ===========================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- ROM: combinational read (address in -> byte out same cycle), matching the
-- 6502's same-cycle read bus (the core samples data_in on the clock edge that
-- ends the cycle).
entity cpu_rom is
  generic (ROM_BITS : positive := 11);
  port (
    addr : in  std_logic_vector(ROM_BITS - 1 downto 0);
    data : out std_logic_vector(7 downto 0)
  );
end entity;

architecture rtl of cpu_rom is
  type rom_t is array (0 to 2 ** ROM_BITS - 1) of std_logic_vector(7 downto 0);
  -- ROM image: assembled by ca65 + ld65 from firmware/mx65_irq_counter_7seg.s
  -- (the readable program) and embedded here verbatim.  The checked-in
  -- firmware/mx65_irq_counter_7seg.bin is the source of truth; regenerate this
  -- aggregate with scripts/embedded_core/rom_to_vhdl.py.  Zero bytes fall through
  -- to `others` (e.g. the RESET vector low byte at offset 16#7FC# = $00).
  constant ROM : rom_t := (
    16#000# => x"78", 16#001# => x"D8", 16#002# => x"A2", 16#003# => x"FF",
    16#004# => x"9A", 16#005# => x"AD", 16#006# => x"04", 16#007# => x"E0",
    16#008# => x"85", 16#009# => x"08", 16#00A# => x"AD", 16#00B# => x"05",
    16#00C# => x"E0", 16#00D# => x"85", 16#00E# => x"09", 16#00F# => x"A9",
    16#011# => x"85", 16#013# => x"85", 16#014# => x"03", 16#015# => x"85",
    16#016# => x"05", 16#017# => x"A2", 16#019# => x"95", 16#01A# => x"10",
    16#01B# => x"E8", 16#01C# => x"E0", 16#01D# => x"08", 16#01E# => x"90",
    16#01F# => x"F9", 16#020# => x"A9", 16#021# => x"01", 16#022# => x"85",
    16#023# => x"01", 16#024# => x"85", 16#025# => x"02", 16#026# => x"85",
    16#027# => x"07", 16#028# => x"20", 16#029# => x"43", 16#02A# => x"F9",
    16#02B# => x"A9", 16#02C# => x"03", 16#02D# => x"8D", 16#02E# => x"12",
    16#02F# => x"E0", 16#030# => x"A9", 16#031# => x"03", 16#032# => x"8D",
    16#033# => x"11", 16#034# => x"E0", 16#035# => x"58", 16#036# => x"4C",
    16#037# => x"36", 16#038# => x"F8", 16#039# => x"48", 16#03A# => x"8A",
    16#03B# => x"48", 16#03C# => x"98", 16#03D# => x"48", 16#03E# => x"AD",
    16#03F# => x"12", 16#040# => x"E0", 16#041# => x"85", 16#042# => x"0C",
    16#043# => x"29", 16#044# => x"01", 16#045# => x"F0", 16#046# => x"08",
    16#047# => x"20", 16#048# => x"63", 16#049# => x"F8", 16#04A# => x"A9",
    16#04B# => x"01", 16#04C# => x"8D", 16#04D# => x"12", 16#04E# => x"E0",
    16#04F# => x"A5", 16#050# => x"0C", 16#051# => x"29", 16#052# => x"02",
    16#053# => x"F0", 16#054# => x"08", 16#055# => x"20", 16#056# => x"7F",
    16#057# => x"F8", 16#058# => x"A9", 16#059# => x"02", 16#05A# => x"8D",
    16#05B# => x"12", 16#05C# => x"E0", 16#05D# => x"68", 16#05E# => x"A8",
    16#05F# => x"68", 16#060# => x"AA", 16#061# => x"68", 16#062# => x"40",
    16#063# => x"C6", 16#064# => x"07", 16#065# => x"D0", 16#066# => x"14",
    16#067# => x"A5", 16#068# => x"06", 16#069# => x"85", 16#06A# => x"07",
    16#06B# => x"20", 16#06C# => x"DF", 16#06D# => x"F8", 16#06E# => x"A5",
    16#06F# => x"02", 16#070# => x"D0", 16#071# => x"06", 16#072# => x"20",
    16#073# => x"1C", 16#074# => x"F9", 16#075# => x"4C", 16#076# => x"7B",
    16#077# => x"F8", 16#078# => x"20", 16#079# => x"08", 16#07A# => x"F9",
    16#07B# => x"20", 16#07C# => x"A7", 16#07D# => x"F8", 16#07E# => x"60",
    16#07F# => x"AD", 16#080# => x"02", 16#081# => x"E0", 16#082# => x"29",
    16#083# => x"01", 16#084# => x"85", 16#085# => x"04", 16#086# => x"F0",
    16#087# => x"10", 16#088# => x"A5", 16#089# => x"03", 16#08A# => x"D0",
    16#08B# => x"0C", 16#08C# => x"A5", 16#08D# => x"01", 16#08E# => x"49",
    16#08F# => x"01", 16#090# => x"85", 16#091# => x"01", 16#092# => x"A5",
    16#093# => x"02", 16#094# => x"49", 16#095# => x"01", 16#096# => x"85",
    16#097# => x"02", 16#098# => x"A5", 16#099# => x"04", 16#09A# => x"85",
    16#09B# => x"03", 16#09C# => x"AD", 16#09D# => x"02", 16#09E# => x"E0",
    16#09F# => x"29", 16#0A0# => x"02", 16#0A1# => x"85", 16#0A2# => x"05",
    16#0A3# => x"20", 16#0A4# => x"43", 16#0A5# => x"F9", 16#0A6# => x"60",
    16#0A7# => x"20", 16#0A8# => x"2F", 16#0A9# => x"F9", 16#0AA# => x"A5",
    16#0AB# => x"05", 16#0AC# => x"F0", 16#0AD# => x"0B", 16#0AE# => x"A9",
    16#0AF# => x"FF", 16#0B0# => x"8D", 16#0B1# => x"20", 16#0B2# => x"E0",
    16#0B3# => x"8D", 16#0B4# => x"21", 16#0B5# => x"E0", 16#0B6# => x"4C",
    16#0B7# => x"C3", 16#0B8# => x"F8", 16#0B9# => x"A5", 16#0BA# => x"0A",
    16#0BB# => x"8D", 16#0BC# => x"20", 16#0BD# => x"E0", 16#0BE# => x"A5",
    16#0BF# => x"0B", 16#0C0# => x"8D", 16#0C1# => x"21", 16#0C2# => x"E0",
    16#0C3# => x"A2", 16#0C5# => x"E4", 16#0C6# => x"09", 16#0C7# => x"B0",
    16#0C8# => x"15", 16#0C9# => x"A5", 16#0CA# => x"05", 16#0CB# => x"F0",
    16#0CC# => x"05", 16#0CD# => x"A9", 16#0CE# => x"FF", 16#0CF# => x"4C",
    16#0D0# => x"D7", 16#0D1# => x"F8", 16#0D2# => x"B4", 16#0D3# => x"10",
    16#0D4# => x"B9", 16#0D5# => x"64", 16#0D6# => x"F9", 16#0D7# => x"9D",
    16#0D8# => x"30", 16#0D9# => x"E0", 16#0DA# => x"E8", 16#0DB# => x"4C",
    16#0DC# => x"C5", 16#0DD# => x"F8", 16#0DE# => x"60", 16#0DF# => x"A5",
    16#0E0# => x"01", 16#0E1# => x"F0", 16#0E2# => x"12", 16#0E3# => x"A6",
    16#0E5# => x"E8", 16#0E6# => x"E4", 16#0E7# => x"08", 16#0E8# => x"90",
    16#0E9# => x"1B", 16#0EA# => x"A6", 16#0EB# => x"08", 16#0EC# => x"CA",
    16#0ED# => x"CA", 16#0EE# => x"86", 16#0F0# => x"A9", 16#0F2# => x"85",
    16#0F3# => x"01", 16#0F4# => x"60", 16#0F5# => x"A6", 16#0F7# => x"F0",
    16#0F8# => x"04", 16#0F9# => x"CA", 16#0FA# => x"86", 16#0FC# => x"60",
    16#0FD# => x"A2", 16#0FE# => x"01", 16#0FF# => x"86", 16#101# => x"A9",
    16#102# => x"01", 16#103# => x"85", 16#104# => x"01", 16#105# => x"86",
    16#107# => x"60", 16#108# => x"A2", 16#10A# => x"F6", 16#10B# => x"10",
    16#10C# => x"B5", 16#10D# => x"10", 16#10E# => x"C9", 16#10F# => x"0A",
    16#110# => x"90", 16#111# => x"09", 16#112# => x"A9", 16#114# => x"95",
    16#115# => x"10", 16#116# => x"E8", 16#117# => x"E4", 16#118# => x"09",
    16#119# => x"90", 16#11A# => x"EF", 16#11B# => x"60", 16#11C# => x"A2",
    16#11E# => x"B5", 16#11F# => x"10", 16#120# => x"D0", 16#121# => x"0A",
    16#122# => x"A9", 16#123# => x"09", 16#124# => x"95", 16#125# => x"10",
    16#126# => x"E8", 16#127# => x"E4", 16#128# => x"09", 16#129# => x"90",
    16#12A# => x"F3", 16#12B# => x"60", 16#12C# => x"D6", 16#12D# => x"10",
    16#12E# => x"60", 16#12F# => x"A9", 16#131# => x"85", 16#132# => x"0B",
    16#133# => x"A9", 16#134# => x"01", 16#135# => x"85", 16#136# => x"0A",
    16#137# => x"A6", 16#139# => x"F0", 16#13A# => x"07", 16#13B# => x"06",
    16#13C# => x"0A", 16#13D# => x"26", 16#13E# => x"0B", 16#13F# => x"CA",
    16#140# => x"D0", 16#141# => x"F9", 16#142# => x"60", 16#143# => x"AD",
    16#145# => x"E0", 16#146# => x"A2", 16#148# => x"A0", 16#149# => x"08",
    16#14A# => x"4A", 16#14B# => x"90", 16#14C# => x"01", 16#14D# => x"E8",
    16#14E# => x"88", 16#14F# => x"D0", 16#150# => x"F9", 16#151# => x"A9",
    16#152# => x"08", 16#153# => x"E0", 16#155# => x"F0", 16#156# => x"09",
    16#157# => x"C9", 16#158# => x"01", 16#159# => x"F0", 16#15A# => x"05",
    16#15B# => x"4A", 16#15C# => x"CA", 16#15D# => x"4C", 16#15E# => x"53",
    16#15F# => x"F9", 16#160# => x"85", 16#161# => x"06", 16#162# => x"60",
    16#163# => x"40", 16#164# => x"3F", 16#165# => x"06", 16#166# => x"5B",
    16#167# => x"4F", 16#168# => x"66", 16#169# => x"6D", 16#16A# => x"7D",
    16#16B# => x"07", 16#16C# => x"7F", 16#16D# => x"6F", 16#7FA# => x"63",
    16#7FB# => x"F9", 16#7FD# => x"F8", 16#7FE# => x"39", 16#7FF# => x"F8",
    others => x"00"
  );
begin
  data <= ROM(to_integer(unsigned(addr)));
end architecture;


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- RAM: combinational read, registered write (latched on the clock edge when the
-- CPU drives rw='0').  Array initialised to zero so a read-before-write returns
-- x"00" rather than 'U' (sim-only metavalue hygiene).
entity cpu_ram is
  generic (RAM_BITS : positive := 11);
  port (
    clk  : in  std_logic;
    we   : in  std_logic;
    addr : in  std_logic_vector(RAM_BITS - 1 downto 0);
    din  : in  std_logic_vector(7 downto 0);
    dout : out std_logic_vector(7 downto 0)
  );
end entity;

architecture rtl of cpu_ram is
  type ram_t is array (0 to 2 ** RAM_BITS - 1) of std_logic_vector(7 downto 0);
  signal ram : ram_t := (others => (others => '0'));
begin
  process (clk) begin
    if rising_edge(clk) then
      if we = '1' then
        ram(to_integer(unsigned(addr))) <= din;
      end if;
    end if;
  end process;
  dout <= ram(to_integer(unsigned(addr)));
end architecture;


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Memory-mapped IO: switch/button/config/tick reads, LED/segment writes, and a
-- free-running prescaler tick.  Read path is combinational; writes + prescaler
-- are clocked.  Generics carry the board resource counts, exposed via config
-- registers so one design fits every board.
entity cpu_io is
  generic (
    NUM_SWITCHES   : positive := 4;
    NUM_BUTTONS    : positive := 4;
    NUM_LEDS       : positive := 4;
    NUM_SEGS       : positive := 4;
    PRESCALER_BITS : positive := 10
  );
  port (
    clk   : in  std_logic;
    cs    : in  std_logic;                      -- IO chip-select (address in $E0xx)
    we    : in  std_logic;                      -- write enable (cpu rw='0')
    addr  : in  std_logic_vector(7 downto 0);   -- low byte of CPU address
    wdata : in  std_logic_vector(7 downto 0);   -- CPU data_out (writes)
    rdata : out std_logic_vector(7 downto 0);   -- to read mux -> CPU data_in
    sw    : in  std_logic_vector(NUM_SWITCHES - 1 downto 0);
    btn   : in  std_logic_vector(NUM_BUTTONS - 1 downto 0);
    led   : out std_logic_vector(NUM_LEDS - 1 downto 0);
    seg   : out std_logic_vector(8 * NUM_SEGS - 1 downto 0);
    irq   : out std_logic  -- interrupt request (level)
  );
end entity;

architecture rtl of cpu_io is
  type seg_array_t is array (0 to NUM_SEGS - 1) of std_logic_vector(7 downto 0);
  signal seg_regs  : seg_array_t := (others => (others => '0'));
  signal led_reg   : std_logic_vector(15 downto 0) := (others => '0');
  signal prescaler : unsigned(PRESCALER_BITS - 1 downto 0) := (others => '0');
  signal tick      : std_logic := '0';
  signal ier        : std_logic_vector(1 downto 0) := "00";
  signal timer_flag : std_logic := '0';
  signal input_flag : std_logic := '0';
  signal prev_sw    : std_logic_vector(NUM_SWITCHES - 1 downto 0) := (others => '0');
  signal prev_btn   : std_logic_vector(NUM_BUTTONS - 1 downto 0) := (others => '0');
  signal sw_ext    : std_logic_vector(15 downto 0);
  signal btn_ext   : std_logic_vector(15 downto 0);
begin
  sw_ext  <= std_logic_vector(resize(unsigned(sw), 16));
  btn_ext <= std_logic_vector(resize(unsigned(btn), 16));

  -- Combinational read mux (one IO register per address).
  process (addr, sw_ext, btn_ext, tick, ier, timer_flag, input_flag) begin
    case addr is
      when x"00"  => rdata <= sw_ext(7 downto 0);
      when x"01"  => rdata <= sw_ext(15 downto 8);
      when x"02"  => rdata <= btn_ext(7 downto 0);
      when x"03"  => rdata <= btn_ext(15 downto 8);
      when x"04"  => rdata <= std_logic_vector(to_unsigned(NUM_LEDS, 8));
      when x"05"  => rdata <= std_logic_vector(to_unsigned(NUM_SEGS, 8));
      when x"06"  => rdata <= std_logic_vector(to_unsigned(NUM_SWITCHES, 8));
      when x"07"  => rdata <= std_logic_vector(to_unsigned(NUM_BUTTONS, 8));
      when x"10"  => rdata <= "0000000" & tick;
      when x"11"  => rdata <= "000000" & ier;
      when x"12"  => rdata <= "000000" & input_flag & timer_flag;
      when others => rdata <= x"00";
    end case;
  end process;

  -- Clocked: prescaler tick (read-to-clear at $E010) + register writes.
  process (clk) begin
    if rising_edge(clk) then
      prescaler <= prescaler + 1;
      if cs = '1' and we = '0' and addr = x"10" then
        tick <= '0';                       -- read-to-clear
      end if;
      if prescaler = (prescaler'range => '1') then
        tick <= '1';                       -- set wins over a simultaneous clear
      end if;
      if cs = '1' and we = '1' then
        case addr is
          when x"20"  => led_reg(7 downto 0)  <= wdata;
          when x"21"  => led_reg(15 downto 8) <= wdata;
          when others =>
            for i in 0 to NUM_SEGS - 1 loop
              if addr = std_logic_vector(to_unsigned(16#30# + i, 8)) then
                seg_regs(i) <= wdata;
              end if;
            end loop;
        end case;
      end if;
    end if;
  end process;

  -- Outputs: LED masked to NUM_LEDS; segment slots packed (digit 0 = rightmost).
  led <= std_logic_vector(resize(unsigned(led_reg), NUM_LEDS));

  process (seg_regs) begin
    for i in 0 to NUM_SEGS - 1 loop
      seg(8 * i + 7 downto 8 * i) <= seg_regs(i);
    end loop;
  end process;

  -- Interrupt controller: two sources (timer + sw/btn change).  Each has an
  -- enable bit (IER $E011) and a flag bit (IFR $E012, write-1-to-clear); irq is
  -- the OR of enabled+pending flags, and the ISR reads IFR to see who fired.
  interrupts : process (clk) begin
    if rising_edge(clk) then
      prev_sw  <= sw;
      prev_btn <= btn;
      -- register writes first, so a same-cycle flag set (below) wins the race
      if cs = '1' and we = '1' then
        if addr = x"11" then
          ier <= wdata(1 downto 0);
        elsif addr = x"12" then
          if wdata(0) = '1' then timer_flag <= '0'; end if;
          if wdata(1) = '1' then input_flag <= '0'; end if;
        end if;
      end if;
      -- flag sources (set wins over a simultaneous ack)
      if prescaler = (prescaler'range => '1') then
        timer_flag <= '1';
      end if;
      if sw /= prev_sw or btn /= prev_btn then
        input_flag <= '1';
      end if;
    end if;
  end process;

  irq <= (timer_flag and ier(0)) or (input_flag and ier(1));
end architecture;


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Top (contract entity): synthesises a power-on reset, instantiates the four
-- blocks, and muxes read data back to the CPU.  COUNTER_BITS is part of the
-- simulator contract but unused by the CPU system; PRESCALER_BITS is a
-- generation-time knob (the wrapper never overrides it).
entity mx65_irq_counter_7seg is
  generic (
    NUM_SWITCHES   : positive := 4;
    NUM_BUTTONS    : positive := 4;
    NUM_LEDS       : positive := 4;
    NUM_SEGS       : positive := 4;
    COUNTER_BITS   : positive := 24;   -- contract generic, unused here
    PRESCALER_BITS : positive := 10
  );
  port (
    clk : in  std_logic;
    sw  : in  std_logic_vector(NUM_SWITCHES - 1 downto 0);
    btn : in  std_logic_vector(NUM_BUTTONS - 1 downto 0);
    led : out std_logic_vector(NUM_LEDS - 1 downto 0);
    seg : out std_logic_vector(8 * NUM_SEGS - 1 downto 0)
  );
end entity;

architecture rtl of mx65_irq_counter_7seg is
  -- CPU bus
  signal cpu_addr : std_logic_vector(15 downto 0);
  signal cpu_din  : std_logic_vector(7 downto 0);
  signal cpu_dout : std_logic_vector(7 downto 0);
  signal cpu_rw   : std_logic;

  -- decode / block outputs
  signal sel_ram, sel_io, sel_rom : std_logic;
  signal ram_we   : std_logic;
  signal io_we    : std_logic;
  signal rom_dout : std_logic_vector(7 downto 0);
  signal ram_dout : std_logic_vector(7 downto 0);
  signal io_dout  : std_logic_vector(7 downto 0);
  signal io_irq   : std_logic;

  -- power-on reset (sim-only, from signal init values)
  signal por_cnt   : unsigned(2 downto 0) := (others => '0');
  signal cpu_reset : std_logic := '1';
begin
  -- POR: hold reset high for the first ~7 clocks, then release.
  process (clk) begin
    if rising_edge(clk) then
      if por_cnt /= "111" then
        por_cnt <= por_cnt + 1;
      end if;
    end if;
  end process;
  cpu_reset <= '1' when por_cnt /= "111" else '0';

  -- Address decode.
  sel_ram <= '1' when cpu_addr(15 downto 11) = "00000" else '0';
  sel_io  <= '1' when cpu_addr(15 downto 8)  = x"E0"   else '0';
  sel_rom <= '1' when cpu_addr(15 downto 11) = "11111" else '0';
  ram_we  <= '1' when (sel_ram = '1' and cpu_rw = '0') else '0';
  io_we   <= not cpu_rw;

  -- Combinational read mux -> CPU data_in (default x"00" keeps the bus defined).
  cpu_din <= rom_dout when sel_rom = '1' else
             io_dout  when sel_io  = '1' else
             ram_dout when sel_ram = '1' else
             x"00";

  cpu : entity work.mx65
    port map (
      clock    => clk,
      reset    => cpu_reset,
      ce       => '1',
      data_in  => cpu_din,
      data_out => cpu_dout,
      address  => cpu_addr,
      rw       => cpu_rw,
      sync     => open,
      nmi      => '0',
      irq      => not io_irq
    );

  rom_inst : entity work.cpu_rom
    generic map (ROM_BITS => 11)
    port map (addr => cpu_addr(10 downto 0), data => rom_dout);

  ram_inst : entity work.cpu_ram
    generic map (RAM_BITS => 11)
    port map (
      clk  => clk,
      we   => ram_we,
      addr => cpu_addr(10 downto 0),
      din  => cpu_dout,
      dout => ram_dout
    );

  io_inst : entity work.cpu_io
    generic map (
      NUM_SWITCHES   => NUM_SWITCHES,
      NUM_BUTTONS    => NUM_BUTTONS,
      NUM_LEDS       => NUM_LEDS,
      NUM_SEGS       => NUM_SEGS,
      PRESCALER_BITS => PRESCALER_BITS
    )
    port map (
      clk   => clk,
      cs    => sel_io,
      we    => io_we,
      addr  => cpu_addr(7 downto 0),
      wdata => cpu_dout,
      rdata => io_dout,
      sw    => sw,
      btn   => btn,
      led   => led,
      seg   => seg,
      irq   => io_irq
    );
end architecture;
